---
- name: Extract node ID from configuration
  set_fact:
    receptor_node_id: "{{ lookup('ini', 'node_id section=default file='+receptor_config_dir+'/'+account_dir+'/receptor.conf') }}"
- name: Identify Satellite source type
  uri:
    url: "https://{{ c_rh_c_host }}/api/sources/v2.0/source_types?name=satellite"
    client_cert: "{{ receptor_config_dir }}/{{ account_dir }}/cert.pem"
    client_key: "{{ receptor_config_dir }}/{{ account_dir }}/key.pem"
    return_content: yes
  register: source_types_response
- name: Extract Satellite source type from response
  set_fact:
    source_type_id: "{{ source_types_response.json | json_query('data[0].id') }}"
- name: See if source already exists
  uri:
    url: "https://{{ c_rh_c_host }}/api/sources/v2.0/sources?name=Satellite%20{{ satellite_uuid }}"
    client_cert: "{{ receptor_config_dir }}/{{ account_dir }}/cert.pem"
    client_key: "{{ receptor_config_dir }}/{{ account_dir }}/key.pem"
    return_content: yes
  register: existing_source_response
- name: Create Source in c.rh.c
  uri:
    url: "https://{{ c_rh_c_host }}/api/sources/v2.0/sources"
    client_cert: "{{ receptor_config_dir }}/{{ account_dir }}/cert.pem"
    client_key: "{{ receptor_config_dir }}/{{ account_dir }}/key.pem"
    method: "POST"
    body:
      name: "Satellite {{ satellite_uuid }}"
      source_type_id: "{{ source_type_id }}"
      source_ref: "{{ satellite_uuid }}"
    body_format: json
    return_content: yes
    status_code:
      - 201
  register: source_create_response
  when: existing_source_response.json.meta.count == 0
- name: Set source ID fact (just created)
  set_fact:
    source_id: "{{ source_create_response.json.id }}"
  when: existing_source_response.json.meta.count == 0
- name: Set source ID fact (pre-existing)
  set_fact:
    source_id: "{{ existing_source_response.json | json_query('data[0].id') }}"
- debug:
    msg: "Source ID {{ source_id }}"
- name: See if endpoint already exists
  uri:
    url: "https://{{ c_rh_c_host }}/api/sources/v2.0/endpoints?source_id={{ source_id }}"
    client_cert: "{{ receptor_config_dir }}/{{ account_dir }}/cert.pem"
    client_key: "{{ receptor_config_dir }}/{{ account_dir }}/key.pem"
    return_content: yes
  register: existing_endpoint_response
- name: Add endpoint to Source
  uri:
    url: "https://{{ c_rh_c_host }}/api/sources/v2.0/endpoints"
    client_cert: "{{ receptor_config_dir }}/{{ account_dir }}/cert.pem"
    client_key: "{{ receptor_config_dir }}/{{ account_dir }}/key.pem"
    method: "POST"
    body:
      source_id: "{{ source_create_response.json.id }}"
      receptor_node: "{{ receptor_node_id }}"
      default: yes
    body_format: json
    status_code:
      - 201
  when: existing_endpoint_response.json.meta.count == 0
